services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "${DB_IP}:${DB_PORT}:5432"
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -p 5432"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  jdrpoly:
    container_name: jdrpoly
    image: jdrpoly
    restart: always
    env_file: .env
    environment:
      - DB_IP=db
      - ORIGIN=http://localhost:3000
    ports:
      - 127.0.0.1:3000:80
    networks:
      - db_network
    depends_on:
      - db

networks:
  db_network:

volumes:
  db:
